version: 2

sources:
  - name: online_retail
    database: cdp-customer-data-platform
    schema: online_retail  
    tables:
      - name: raw
        columns:
          - name: InvoiceNo
            tests:
              - not_null
              - dbt_expectations.expect_column_to_exist
              - dbt_expectations.expect_column_values_to_be_of_type:
                  column_type: string

          - name: StockCode
            tests:
              - dbt_expectations.expect_column_to_exist

          - name: Description
            tests:
              - dbt_expectations.expect_column_to_exist

          - name: Quantity
            tests:
              - dbt_expectations.expect_column_to_exist
              - dbt_expectations.expect_column_values_to_be_of_type:
                  column_type: numeric

          - name: InvoiceDate
            tests:
              - dbt_expectations.expect_column_to_exist

          - name: UnitPrice
            tests:
              - dbt_expectations.expect_column_to_exist
              - dbt_expectations.expect_column_values_to_be_of_type:
                  column_type: numeric

          - name: CustomerID
            tests:
              - dbt_expectations.expect_column_to_exist

          - name: Country
            tests:
              - dbt_expectations.expect_column_to_exist


models:
  - name: dim_customer
    description: "Customer dimension"
    columns:
      - name: customer_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: dim_datetime
    description: "Datetime dimension"
    columns:
      - name: datetime_id
        description: "The primary key for this table"
        tests:
          - not_null
          - unique

  - name: dim_product
    description: "Product dimension"
    columns:
      - name: product_id
        description: "The primary key for this table"
        tests:
          - not_null
          - unique

  - name: fct_invoice
    description: "Fact table"
    tests:
      - dbt_utils.expression_is_true:
          expression : "total_value != 0"
      - dbt_utils.fewer_rows_than:
          compare_model: source('online_retail','raw')
    columns:
      - name: invoice_id
        description: "The primary key for this table"
        tests:
          - not_null
          - dbt_expectations.expect_column_to_exist

      - name: datetime_id
        tests:
          - dbt_expectations.expect_column_to_exist
          - relationships:
              to: ref('dim_datetime')
              field: datetime_id

      - name: customer_id
        tests:
          - dbt_expectations.expect_column_to_exist
          - relationships:
              to: ref('dim_customer')
              field: customer_id

      - name: product_id
        tests:
          - dbt_expectations.expect_column_to_exist
          - relationships:
              to: ref('dim_product')
              field: product_id

      - name: status
        tests:
          - dbt_expectations.expect_column_to_exist
          - accepted_values:
              values: ['Cancel','Succeed']
      - name: total_value
        tests:
        - dbt_expectations.expect_column_to_exist
    

